# This is a basic workflow to help you get started with Actions

name: PROD - MAIN

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  repo-update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: executing remote ssh commands using token
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.T_HOST_IP }}
          username: ${{ secrets.T_USERNAME }}
          password: ${{ secrets.T_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            START=`date +"%T"`
            cd /var/www/fivemods/html
            git pull https://${{ secrets.TOKEN }}@github.com/FiveMods/fivemods.net.git master
            END=`date +"%T"`
            COMMIT=`git log -n 1 | grep -e "commit" | awk '{ print $2 }'`
            GHUSER=`git log -n 1 | grep -e "Author" | cut -d " " -f 2`
            echo "[`date`] - [$START-$END] - [<a href="https://github.com/FiveMods/fivemods.net/commit/$COMMIT" target="_blank" rel="noopener noreferrer">$COMMIT</a>] - [$GHUSER] - Run complete. <br>" >> prod.html
