# This is a basic workflow to help you get started with Actions

name: Master CI/CD Service

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push: 
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell      
      - name: PHP & Apache status
        uses: garygrossgarten/github-action-ssh@v0.5.0
        with:
          command: php -v && systemctl status apache2  
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
#'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell      
      - name: Run Web-Updater
        uses: garygrossgarten/github-action-ssh@v0.5.0
        with:
          command: cat premotd.txt && echo "Starttime:" && date +"%T" && cd /var/www/ && pwd && cd fivemods/ && rm -rfv pre-live-html/ && git clone https://${{ secrets.UNAME }}:${{ secrets.UPW }}@github.com/FiveMods/fivemods.net.git && ls -l && pwd && mv fivemods.net pre-live-html/ && chmod 755 pre-live-html && echo "Done, moved to pre-live checkout on https://pre-live.fivemods.net/." && echo "Stoptime:" && date +"%T" && exit
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
  control:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell      
      - name: Apache restart and apache run control
        uses: garygrossgarten/github-action-ssh@v0.5.0
        with:
          command: systemctl status apache2 && systemctl restart apache2 && systemctl status apache2 && cd /var/www/fivemods/pre-live-html && cat CHECK.md && exit
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
